reads_fq: evaluation/test_data/benchmark/Shigella_flexneri/nanopore.fastq.gz
output_dir: evaluation/output

threads: 4
paf: alignments.paf
min_read_length: 1000
min_base_quality: 10.0
genome_size: 6741160

min_overlap_length: 2000
min_overlap_count: 3
min_percent_identity: 5.0
overhang_ratio: 0.8

output_prefix: unitigs
max_bubble_length: 100
min_support_ratio: 1.1
max_tip_len: 4
fuzz: 10
cleanup_iterations: 3
short_edge_ratio: 0.8

completion_enabled: false
completion_rounds: 1
completion_min_alignment_len: 2000
completion_min_identity: 0.8

coverages: [5, 10, 15, 20, 25, 30, 35, 40, 45, 50]

ilesta_path: target/debug/Ilesta